services:
  # TODO use secrets for confidential variables in .env file
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./.env:/app/.env
    depends_on:
      embedding-service:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - PORT=3000
    volumes:
      - ./.env:/app/.env
    depends_on:
      - backend

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "${ADMIN_PORT}:3000"
    environment:
      - PORT=3000
    volumes:
      - ./.env:/app/.env
    depends_on:
      - backend

  embedding-service:
    build:
      context: ./embedding-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
