services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    env_file: .env
    depends_on:
      - database

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "$DB_PORT:$DB_PORT"
    env_file: .env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
